### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by zcyc** [AgoraIO-Community/go-tokenbuilder#3]
I want to make a token server, does this package still work?

@plutoless @digitallysavvy

**Comment by digitallysavvy** [comment]
To my knowledge yes. This code is from this repo https://github.com/AgoraIO/Tools/tree/master/DynamicKey/AgoraDynamicKey/go but was extracted here as an easier way to pull it into a Go Module as part of the Docker implementation in this project https://github.com/AgoraIO-Community/agora-token-service
